mysite/food/urls.py
from django.urls import path
from . import views

app_name = 'food'
urlpatterns = [
    path('',views.IndexClassView.as_view(),name='index'),
    path('item/',views.item,name='item'),
    path("<int:pk>/",views.DetailClassView.as_view(),name='detail'),
    #add items
    path('add',views.CreateItem.as_view(),name='create_item'),
    #edit items
    path('update/<int:id>/',views.update_item,name='update_item'),
    #delete items
    path('delete/<int:id>/',views.delete_item,name='delete_item')

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('',views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name = 'users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name = 'users/logout.html'),name='logout'),
    path('profile/',views.profilepage,name='profile')


]

urlpatterns += [ 

] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Item(models.Model):
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length = 500,default='https://media.istockphoto.com/vectors/illustration-icon-with-the-concept-of-food-donation-vector-id951697932?k=6&m=951697932&s=612x612&w=0&h=cewzX5-oehPnBVufvbWBLbRfvRA_Bh0OouWgHZjzwH0=')

    def __str__(self) -> str:
        return self.item_name 

    def get_absolute_url(self):
        return reverse('food:detail',kwargs={'pk':self.pk})

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default = 'profile.jpg',upload_to = 'profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.user.username

mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

mysite/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.db import models
from django.forms import fields

class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

mysite/food/views.py
from django.db import models
from .forms import ItemForm
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Item
from django.views.generic import ListView,DetailView,CreateView


class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'items'
    

def item(request):
    return HttpResponse("Hi im Krish Anjel")
   

class DetailClassView(DetailView):
    model = Item
    template_name = 'food/detail.html'
   

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form})
#this is a class based item for create item

class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/item-form.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)



def update_item(request,id):
    item = Item.objects.get(id= id)
    form = ItemForm(request.POST or None,instance= item)
    if form.is_valid():
        form.save()
        return redirect("food:index")
    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item = Item.objects.get(id = id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request,'food/item-delete.html',{'item':item})

    

mysite/users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegistrationForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username').capitalize()
            messages.success(request,f'Welcome {username} Hurrayyy!!! Your account is successfully created')
            form.save()
            return redirect('login')
    else:
        form = RegistrationForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'food/butterfly.png' %}">
    <title>Anjelina</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark ">
        <a href="#" class="navbar-brand">FoodApp</a>
        <a href="../"><input type="button" value="Back" class="btn btn-light" /></a>


        <div class="navbar ">
            <a  href="{% url 'food:create_item' %}" style="color: green;" class="nav-item nav-link btn btn-outline-success btn-sm" >Add item</a>
            {% if user.is_authenticated %}
            <a class="btn btn-primary btn-sm" href="{% url 'logout' %}">Logout</a>
            <a  class="btn btn-success btn-sm" href="{% url 'profile' %}">Profile</a>
            {% else %}
            <a class="btn btn-primary btn-sm" href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
     </nav>
     {% if messages %}
     {% for message in messages %}
      <div class="alert alert-{{message.tags}}">
          {{message}}
      </div>
     {% endfor %}
     {% endif %}
     {% block content %}
     {% endblock %}
</body>
</html>

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="img-fluid mb-2">
            <img  height="300px" src="{{object.item_image}}"/>
        </div>
        <div class="img-fluid mb-2">
            <h1>{{object.item_name}}</h1>
            <h2><p>{{object.item_desc}}</h2>
            <h3>${{object.item_price}}</h3>
            <a class="btn btn-danger" href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
   {% block content %}
   <br>
   <h3>Hey!!! {{user.username}} Nice to meet You again...</h3>
   <br>
   {% for item in items %}

   <div class="row">
       <div class="col-md-3 offset-md-2">
        <img src="{{item.item_image}}" class="img-fluid mb-2" height="150px"/>
       </div>
       <div class="col-md-4">
        <h3>{{ item.item_name }}</h3>
        <h5>{{ item.item_desc|truncatechars:50}}</h5>
        <h6>${{ item.item_price}}</h6>
       </div>
       <div class="col-md-2">
       <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
       <a href="{% url 'food:update_item' item.id %}" class="btn btn-info">Update</a>

       </div>
   </div>

   {% endfor %}
   {% endblock %}
   <h1>Hi im krish anjel</h1>
   <ul>
       <li>
        <a href="{% url 'food:detail' item.id %}"> {{item.id}} - {{item.item_name}} </a>
    </li>  
   </ul>
   
   </body>
</html>

mysite/food/templates/food/item-delete.html
{% extends 'food/base.html' %}
{% block content %}

<form method="POST">
    {% csrf_token %}

    <center>
        <h2>Are You sure You want to delete {{ item.item_name }}</h2>
        <button class="btn btn-success" type="submit">Confirm</button>
    </center>
</form>

{% endblock %}

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info ">
                    <div class="card-title">
                        Wow!!! You are going to add a new-item
                    </div>
                    </div>
                    <div class="card-body">
                    
                            <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="form-group">
                               {{field.name}}
                               <br>
                               {{field}}
                            </div>
                            {% endfor %}
                            <br>
                            <button class="btn btn-primary" type="submit">Save</button>
                            </form>
                            
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .container{
        margin-top: 40px;
        font-weight: bold;
    }
    .card-title{
        color:#fff;
    }
</style>
{% endblock %}

mysite/food/templates/food/update.html
{% extends 'food/base.html' %}
{% block content %}
{% endblock %}

mysite/users/templates/users/login.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="shortcut icon" type="image/png" href="{% static 'users/butterfly.png' %}">

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 ">
            <div class="card">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        <b>Login</b>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <center>
                            {{form.as_p}}
                         <button class="btn btn-info" type="submit">Login</button>
                        </center>    
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .container{
        margin-top: 10%;
    }
    .btn {
      border-radius: 50%;
      color: #fff;
    }
    b{
        font-size: x-large;
    }
</style>

mysite/users/templates/users/logout.html
{% load static %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="shortcut icon" type="image/png" href="{% static 'users/butterfly.png' %}">


<center>
    <h2>You have been successfully logged out</h2>
    <a class="btn btn-primary" href="{% url 'register' %}">Sign Up</a>
    <a class="btn btn-primary" href="{% url 'login' %}">Login</a>
</center>
<style>
    h2, a{
      margin-top: 25px;
    }
</style>

mysite/users/templates/users/profile.html
{% load static %}

<link rel="shortcut icon" type="image/png" href="{% static 'users/butterfly.png' %}">

<center>
    <h2>{{user.username}}'s Profile</h2>
<img height="400px" width="400px" src="{{user.profile.image.url}}">
</center>

mysite/users/templates/users/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'users/butterfly.png' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Login Page</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
              <div class="card">
                  <div class="card-header bg-info">
                      <div class="card-title">
                          <b>Register</b>
                      </div>
                      </div>
                      <div class="card-body"><form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                        {{field.name}}
                                        <br>
                                        {{field}}

                                </div>
                        
                                {% endfor %}
                                <br>
                                <button class="btn btn-primary" type="submit">Sign up</button>
                                <a class="btn btn-primary" href="{% url 'login' %}">Login</a>
                                </form>
                        
                     </div>
                  </div>
              </div>
            </div>
        </div>
    </div>
</body>
<style>
    .container{
        margin-top: 7%;
    }
    .card-title{
        color: #fff;
        font-size: xx-large;
    }
</style>
</html>